# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6404594219e23064ee05cc87621298a7269682c3fa40154fe2fd32969df91b3dbcbb8a9f6c0a93a6154a83bc76f2ab44ad6725509aa5c5fd20427dfdc44c24b

test:
  secret_key_base: 0d9b0843b742424f5350e6d6c0fc2c828247284a99dafa57899a3932ec87a57f7154a9816db750e28255c8b97c0c735154e4dd811044c6d8039670a82714222d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
